// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NuGetManagerSlim
{
    internal sealed partial class Vsix
    {
        public const string Id = "NuGetManagerSlim.02b52d4a-302c-45d8-9d1f-9cc4759f30be";
        public const string Name = "NuGet Manager Slim";
        public const string Description = @"An alternative NuGet Package Manager for Visual Studio — unified, async-first, with inline progress and per-framework version state.";
        public const string Language = "en-US";
        public const string Version = "1.0.901";
        public const string Author = "Mads Kristensen";
        public const string Tags = "nuget, package manager, packages";
        public const bool IsPreview = false;
    }
}
