// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NuGetManagerSlim
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string NuGetManagerSlimString = "f6649f79-8c76-4df8-ae04-370c692ed6ed";
        public static Guid NuGetManagerSlim = new Guid(NuGetManagerSlimString);

        public const string ImageCatalogGuidString = "ae27a6b0-e345-4288-96df-5eaf394ee369";
        public static Guid ImageCatalogGuid = new Guid(ImageCatalogGuidString);

        public const string DotNetProjectContextString = "9b254846-1ea2-451c-b07c-4ac6a8c64f37";
        public static Guid DotNetProjectContext = new Guid(DotNetProjectContextString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NuGetQuickManagerGroup = 0x1020;
        public const int NuGetQuickManagerToolbar = 0x1100;
        public const int NuGetQuickManagerToolbarGroup = 0x1101;
        public const int NuGetQuickManagerToolbarRefreshGroup = 0x1102;
        public const int ViewModeMenuController = 0x1104;
        public const int ViewModeMenuGroup = 0x1105;
        public const int ViewModeBrowseCommand = 0x0210;
        public const int ViewModeInstalledCommand = 0x0211;
        public const int ViewModeUpdatesCommand = 0x0212;
        public const int RefreshCommand = 0x0203;
        public const int OpenForProjectCommand = 0x0204;
        public const int ProjectContextGroup = 0x1200;
        public const int SolutionContextGroup = 0x1201;
        public const int OpenForSolutionCommand = 0x0205;
        public const int StatusUpdateAvailable = 0x0F82;
    }
}
