// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NuGetManagerSlim
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string NuGetManagerSlimString = "f6649f79-8c76-4df8-ae04-370c692ed6ed";
        public static Guid NuGetManagerSlim = new Guid(NuGetManagerSlimString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int NuGetQuickManagerGroup = 0x1020;
        public const int OpenNuGetQuickManagerCommand = 0x0101;
        public const int NuGetQuickManagerToolbar = 0x1100;
        public const int NuGetQuickManagerToolbarGroup = 0x1101;
        public const int NuGetQuickManagerToolbarRefreshGroup = 0x1102;
        public const int FilterInstalledCommand = 0x0200;
        public const int FilterUpdatesCommand = 0x0201;
        public const int FilterPrereleaseCommand = 0x0202;
        public const int RefreshCommand = 0x0203;
    }
}
